version: '3'

services:
  db:
    container_name: billboarddb
    image: postgres
    hostname: db
    environment:
      GET_HOST_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    networks:
      - billboardnet

  billboardapi:
    container_name: billboardapi
    image: billxsheng/billboardapi:v1
    hostname: billboardapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
    networks:
      - billboardnet
    volumes:
      - .:/go/src/billboardAPI
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer

networks:
  billboardnet:
    driver: bridge